image:
  name: hashicorp/terraform:1.6.0
  entrypoint: [""]

stages:
  - validate
  - plan
  - apply
  - destroy

before_script:
  - terraform init

validate:
  stage: validate
  script:
    - terraform fmt -check
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    name: plan
    paths:
      - tfplan
    expire_in: 1 week

apply:
  stage: apply
  script:
    - terraform apply -input=false tfplan
  dependencies:
    - plan
  only:
    - main

destroy:
  stage: destroy
  script:
    - terraform destroy --auto-approve
  when: manual
  only:
    - main